### ISSUE TITLE
Apps ready for the 64-bit requirement by August 1, 2019

### ISSUE THREAD

**Issue by tanjaveg** [ooMICAHoo/dmsounds#38]
Are apps made with Cordova mobile development framework already 64-bit ready and compatible? Since we are developing in non-native code (Cordova), is the requirement related to us?

**Comment by ooMICAHoo** [comment]
Shoot, I don't have a clue :/ I'm going to go ahead and close this cause I'm using this page for tracking issues for my app DM Sounds.. Good luck
